# Copyright 2022 Kubespider
# SPDX-License-Identifier: Apache-2.0

name: Kubespider release for DockerHub and AliyunHub
on:
  push:
    tags:
      - "extension-v*.*.*"
jobs:
  Release-Extension:
    name: Release Kubespider Chrome Extension
    runs-on: ubuntu-20.04
    steps:
    - name: Extract Release Tag and Commit SHA
      id: vars
      shell: bash
      run: |
        echo "release_tag=$(echo ${GITHUB_REF#refs/tags/extension-})" >> $GITHUB_ENV
        echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    # pack zip and read manifest, can be reused in the following steps
    - id: packExtensionDir
      uses: cardinalby/webext-buildtools-pack-extension-dir-action@v1
      with:
        extensionDir: 'extension'
        zipFilePath: 'build/extension-${{env.release_tag}}.zip'

    - name: Upload Release Manifests
      uses: softprops/action-gh-release@v1
      with:
        name: Chrome Extension ${{env.release_tag}}
        files: |
          build/extension-${{env.release_tag}}.zip
